name: Compute Benchmark Matrix

on:
  workflow_call:
    inputs:
      max-runners:
        required: true
        type: string
    outputs:
      matrix:
        description: "The generated matrix for sharding"
        value: ${{ jobs.gen.outputs.matrix }}

jobs:
  gen:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.gen.outputs.matrix }}
    steps:
      - id: gen
        run: |
          n="${{ inputs.max-runners }}"
          shards=$(seq 0 $((n-1)) | paste -sd, -)
          echo "matrix={\"shard\": [${shards}], \"num_shards\": [${n}]}" >> $GITHUB_OUTPUT
